// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using s16508_kolokwium;

namespace s16508_kolokwium.Migrations
{
    [DbContext(typeof(MusicDbContext))]
    [Migration("20200621093337_addedMusicLabelTable")]
    partial class addedMusicLabelTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("s16508_kolokwium.Models.Album", b =>
                {
                    b.Property<int>("IdAlbum")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AlbumName");

                    b.Property<int?>("IdMusicLabel");

                    b.Property<DateTime>("PublishDate");

                    b.HasKey("IdAlbum");

                    b.HasIndex("IdMusicLabel");

                    b.ToTable("Albums");
                });

            modelBuilder.Entity("s16508_kolokwium.Models.MusicLabel", b =>
                {
                    b.Property<int>("IdMusicLabel")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("IdMusicLabel");

                    b.ToTable("MusicLabels");
                });

            modelBuilder.Entity("s16508_kolokwium.Models.Track", b =>
                {
                    b.Property<int>("IdTrack")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<float>("Duration");

                    b.Property<int?>("IdAlbum");

                    b.Property<string>("TrackName");

                    b.HasKey("IdTrack");

                    b.HasIndex("IdAlbum");

                    b.ToTable("Tracks");
                });

            modelBuilder.Entity("s16508_kolokwium.Models.Album", b =>
                {
                    b.HasOne("s16508_kolokwium.Models.MusicLabel")
                        .WithMany("Albums")
                        .HasForeignKey("IdMusicLabel");
                });

            modelBuilder.Entity("s16508_kolokwium.Models.Track", b =>
                {
                    b.HasOne("s16508_kolokwium.Models.Album", "Album")
                        .WithMany("Tracks")
                        .HasForeignKey("IdAlbum");
                });
#pragma warning restore 612, 618
        }
    }
}
